### ISSUE TITLE
Chose tables to work on

### ISSUE THREAD

**Issue by ramezrafla** [Gelembjuk/oursql#5]
@Gelembjuk 
Is it possible to chose which tables we want blockchains with?
Not every table has to be secured, for example, user / system settings etc.

I would still want the tables to be replicated on other nodes, just not blockchained.

If this is not implemented, can you guide us where to make the changes in the code?

We'll PR back

PS: This is for an enterprise ERP application, where financials and critical data need to be controlled, but not settings or less critical data.

**Comment by Gelembjuk** [comment]
yes. There is the option
"UnmanagedTables" option in the consensus config file.
Every node should be delivered with a cosensus config file. It defines rules of consensus and some settings related to DB tables.

There is example of such config file . Some time ago i tried to build Wordpress over blockchain. It was almost success, but i had no time to complete it

I think this example will give you a hint on how to control tables
```{
    "Application": {
        "Name":"MyBlockchainApp",
        "WebSite":"http://oursql.org",
        "Team":"Application Support Team"
    },
    "Kind":"proofofwork",
    "CoinsForBlockMade":10.0,
    "Settings":{
        "Complexity":16,
        "ComplexityStep2":24,
        "MaxMinNumberTransactionInBlock":1000,
        "MaxNumberTransactionInBlock":10000
    },
    "DBSettings":{
        "IncompatibleSSLModes":["ONLY_FULL_GROUP_BY"]
    },
    "AllowTableCreate":false,
    "AllowTableDrop":false,
    "AllowRowDelete":false,
    "TransactionCost":{
        "Default":10.0
    },
    "UnmanagedTables":["wp_options","wp_postmeta","wp_usermeta","wp_term_relationships","wp_term_taxonomy","wp_termmeta","wp_terms","wp_links"],
    "UnmanagedTablesImport":["wp_options","wp_postmeta","wp_usermeta","wp_term_relationships","wp_term_taxonomy","wp_termmeta","wp_terms","wp_links"],
    "PaidTransactionsWallet":"1K4BQWE1adfFRQA3Epnc3kdjNNR9vH6bg9",
    "TableRules":[
        {
            "Table":"wp_users",
            "AllowRowDelete":false,
            "AllowRowUpdate":true,
            "AllowRowInsert":true,
            "TransactionCost":{
                "Default":10.0,
                "RowInsert":4.0,
                "RowUpdate":1.0
            }
        },
        {
            "Table":"wp_posts",
            "AllowRowDelete":false,
            "AllowRowUpdate":true,
            "AllowRowInsert":true,
            "TransactionCost":{
                "Default":10.0,
                "RowInsert":1.0,
                "RowUpdate":0.1
            }
        },
        {
            "Table":"wp_comments",
            "AllowRowDelete":false,
            "AllowRowUpdate":true,
            "AllowRowInsert":true,
            "TransactionCost":{
                "Default":10.0,
                "RowInsert":0.1,
                "RowUpdate":0.01
            }
        }
    ],
    "InitNodesAddreses":[]
}```

**Comment by ramezrafla** [comment]
Thanks @Gelembjuk 

The docs say:
`There can be tables in a DB which are not required to sync between nodes. TO keep some local data. Such tables can be just listed in an array.`

OurSQL will therefore not sync them, right? We have to sync manually with MySQL

**Comment by Gelembjuk** [comment]
If a table is in "ignore list", it can be manipulated  through OurSQL and it will not try to blockchain it, just works like a proxy to mysql .
It can be used to store some data specifi only to a local node and not replicated to all other nodes.
it work for local settings or so

**Comment by ramezrafla** [comment]
Got it, we'll have to sync it via mysql directly then. In the future we could add it to OurSQL so it is a single replication interface.

Thanks so much for your help!
